batch_size: 256
capacity: 10000
env: !!python/object:RLEnv.RLEnv
  AVG_ANGLE_DIFFERENCE: 0
  AVG_CAR_SPEED: 2.0
  AVG_DISTANCE_TO_NEXT_SEGMENT: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    KxQjh8XSaEA=
  AVG_RAY_LENGTH: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    69Rnb1oGXEA=
  CRASH_REWARD: -2
  GOAL_REWARD: 1
  LIFE_REWARD: 0
  MAXIMUM_STEPS: 5000
  STD_ANGLE_DIFFERENCE: 180
  STD_CAR_SPEED: 1
  STD_DISTANCE_TO_NEXT_SEGMENT: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    NOp4q8xVSkA=
  STD_RAY_LENGTH: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    LH0Pw56iU0A=
  USELESS_ACTION_REWARD: -0.5
  action_record: !!python/object:Record.Record
    current_value: null
    dir_name: actions_records__2024_07_28_09_51_28
    name: actions
    record: []
    replay_records: []
    separator: ;
    set_time_in_file_name: true
    start_time: ''
  action_space: !!python/object:ActionSpace.ActionSpace
    actions:
    - 0
    - 1
    - 2
    - 3
    - 4
    descriptive_actions:
    - hold
    - accelerate
    - decelerate
    - steer_left
    - steer_right
    n: 5
  auto_config_car_start: true
  background: !!python/object/apply:shapely.io.from_wkb
  - !!binary |
    AQMAAAABAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIJAAAAAAAAAiUAAAAAA
    AMCCQAAAAAAAAIlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  car: !!python/object:Car.Car
    acceleration: 0.1
    car_angle: 197.01828425567416
    car_speed: 0
    car_x: 657.75
    car_y: 141.0
    max_backward_speed: 0
    max_forward_speed: 4
    turn_angle: 5
  current_segmented_track_index: 0
  current_step: 0
  height: 600
  image_path: map1.png
  inverse_track: !!python/object/apply:shapely.io.from_wkb
  - !!binary |
    AQYAAAACAAAAAQMAAAACAAAABQAAAAAAAAAAAAAAAAAAAADAgkAAAAAAAACJQAAAAAAAwIJAAAAA
    AAAAiUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIJAFQAAAAAAAAAAuIVA
    AAAAAADAV0AAAAAAAIiGQAAAAAAAQGxAAAAAAACIhkAAAAAAABB5QAAAAAAAGIZAAAAAAABwfEAA
    AAAAABiEQAAAAAAAwIBAAAAAAABogEAAAAAAAPCAQAAAAAAAgH1AAAAAAABIgEAAAAAAAGB7QAAA
    AAAAUHhAAAAAAADgeUAAAAAAAOB1QAAAAAAAUHdAAAAAAACQeUAAAAAAANB0QAAAAAAAsH9AAAAA
    AABAaEAAAAAAANB/QAAAAAAAwF5AAAAAAAAwfkAAAAAAAIBZQAAAAAAAsHxAAAAAAAAAW0AAAAAA
    AJBwQAAAAAAAIGRAAAAAAAAAW0AAAAAAAABnQAAAAAAAQFVAAAAAAACQekAAAAAAAABHQAAAAAAA
    iIFAAAAAAAAARkAAAAAAABiEQAAAAAAAAE5AAAAAAAC4hUAAAAAAAMBXQAEDAAAAAQAAABUAAAAA
    AAAAAOiDQAAAAAAAYGVAAAAAAACQc0AAAAAAAOBhQAAAAAAAoHFAAAAAAAAAZEAAAAAAAMBuQAAA
    AAAAAGRAAAAAAABAa0AAAAAAAEBnQAAAAAAAoGVAAAAAAABQc0AAAAAAAOBjQAAAAAAA0HdAAAAA
    AACgZ0AAAAAAAKB5QAAAAAAAAG5AAAAAAADgekAAAAAAACBxQAAAAAAA8HpAAAAAAABAckAAAAAA
    AMB5QAAAAAAAkHNAAAAAAAAAdUAAAAAAAOB2QAAAAAAAUHBAAAAAAADAe0AAAAAAAKBvQAAAAAAA
    oH5AAAAAAACgckAAAAAAAFiAQAAAAAAAUHtAAAAAAAAwgkAAAAAAAMB8QAAAAAAAEIRAAAAAAABg
    eEAAAAAAAKCEQAAAAAAA0HVAAAAAAACAhEAAAAAAAMBtQAAAAAAA6INAAAAAAABgZUA=
  number_of_rays: 9
  rays:
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQJ8IcEfrNn5AFdJ+wFG3Y0A=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQHxbjzRA8oJAfbqDtgwLZUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQDj/SWwoyoNAu/+XKK9VZUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQPUtHUyBFIRAiub5dMHTZ0A=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQHTVeFkr5IBAEhlrY4wmRkA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQKzBmceLG4NAsCpK2dnrSkA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQMAD++GqU4RASE9bXklBUEA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQO6mIzFNHoVAFzRxkmSEVEA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACOhEAAAAAAAKBhQAHx+YyHY3dAgZ2uO9QbS0A=
  reward_lines:
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAADohEAAAAAAAGBTQAAAAAAANIRAAAAAAACQaUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAADQgkAAAAAAAABKQAAAAAAAsH1AAAAAAACgY0A=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAQAAAAAIc0AAAAAAAGBQQAAAAAAAmHJAAAAAAADwYkA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACQZUAAAAAAACBYQAAAAAAAAG1AAAAAAACgZUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAADQYEAAAAAAAFBnQAAAAAAAcGhAAAAAAADwbkA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAABAWkAAAAAAAKB2QAAAAAAAwGRAAAAAAACQdUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAAAgXEAAAAAAAHB9QAAAAAAAwGVAAAAAAAC4eEA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAADQY0AAAAAAAAB/QAAAAAAA0GpAAAAAAABAekA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAAB4cEABAAAAAMB/QAAAAAAAEHBAAAAAAADoekA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAAAQdkAAAAAAAKB8QAAAAAAAsHFAAQAAAABYekA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAACYeEAAAAAAALh3QAAAAAAA6HJAAAAAAABgd0A=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAQAAAACgekAAAAAAABh3QAEAAAAAqH9AAAAAAAD4dkA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAABwfEAAAAAAAHB8QAAAAAAARIFAAAAAAAAIfEA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAABAgkAAAAAAANiAQAAAAAAAIINAAAAAAACQekA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAQAAAAAYhUD///////d+QAAAAAAAWIRAAAAAAAAYd0A=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQIAAAACAAAAAAAAAABQhkAAAAAAAMB6QAAAAAAAkIRAAAAAAABYckA=
  save_processed_track: true
  segmented_track_in_order:
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAAEgAAAAAAAAAAkHpAAAAAAAAAR0B7tVYKAAhzQBPHTvn/X1BAMZVqCgAIc0Dlfi77
      /19QQPX3ewoACHNAKutJ//9fUECegXMKAAhzQFcYZwMAYFBAdBADCwCYckCAH+zz/+9iQAAAAAAA
      kHNAAAAAAADgYUAAAAAAAOiDQAAAAAAAYGVAfwy5/P8zhEBsX8bR/49pQEBn1vr/54RA8N6u+P9f
      U0COt/P6/+eEQNWTq/T/X1NA4nkd+//nhEB8N8Tw/19TQEZHU/v/54RAvWkC7f9fU0AXm5T7/+eE
      QNltb+n/X1NARIyn+//nhECV35no/19TQAAAAAAAGIRAAAAAAAAATkAAAAAAAIiBQAAAAAAAAEZA
      AAAAAACQekAAAAAAAABHQA==
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAAFQAAAAAAAAAAQGtAAAAAAABAZ0AAAAAAAMBuQAAAAAAAAGRAAAAAAACgcUAAAAAA
      AABkQLr/zvb/l3JA+7UUCgDwYkCawWH2/5dyQM1UWggA8GJA6tAE9v+XckC1WW0GAPBiQNR7wPX/
      l3JAIoZwBADwYkDQapX1/5dyQI3AaAIA8GJADAiE9f+XckBrClsAAPBiQGN+jPX/l3JA1XNM/v/v
      YkDO0Vb1/wdzQD+b5gYAYFBAAAAAAAAAZ0AAAAAAAEBVQAAAAAAAIGRAAAAAAAAAW0B6X7MGANBg
      QLmcJuz/T2dAG4QGCADQYECk9Z/s/09nQL7K4gkA0GBApTiB7f9PZ0DqsaYLANBgQN4UkO7/T2dA
      ft9NDQDQYECG7snv/09nQClA1A4A0GBA178r8f9PZ0CotPEHAHBoQFY0Ser/725AAAAAAABAa0AA
      AAAAAEBnQA==
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAADwAAAAAAAAAA4GNAAAAAAADQd0AAAAAAAKBlQAAAAAAAUHNAAJbN+P9vaECI7qsT
      APBuQOV7+ff/b2hAXApgEwDwbkBCNR32/29oQFvHfhIA8G5AFk5Z9P9vaEAi628RAPBuQIIgsvL/
      b2hAehE2EADwbkDXvyvx/29oQClA1A4A8G5AHMyD+P/PYEBuTCwWAFBnQAAAAAAAAFtAAAAAAACQ
      cEAAAAAAAIBZQAAAAAAAsHxAcub74/8fXEAg1P73/299QCt9ve//v2VAM6xg+f+3eEBVI+7w/79l
      QOFdt/j/t3hAAAAAAADgY0AAAAAAANB3QA==
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAADQAAAAAAAAAAAG5AAAAAAADgekAAAAAAAKBnQAAAAAAAoHlAP/0hDwDAZUCabVAH
      ALh4QKkFhSAAIFxAzVOfBgBwfUAUQMQdACBcQKApYwcAcH1Af7OXGwAgXEBJM+IHAHB9QAAAAAAA
      wF5AAAAAAAAwfkAAAAAAAEBoQAAAAAAA0H9Ar3d99f93cEBztiYAAMB/QIkJjfX/D3BAClrgAADo
      ekB47YP1/w9wQEYU2f//53pAoHiG9f8PcECqIbH//+d6QAAAAAAAAG5AAAAAAADgekA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAADQAAAAAAAAAAQHJAAAAAAADAeUAAAAAAACBxQAAAAAAA8HpA13CMCgAQcEC7bE8A
      AOh6QHf2cgoAeHBA96Uf//+/f0AFZHkKAHhwQDlr2f//v39AAAAAAADQdEAAAAAAALB/QAAAAAAA
      UHdAAAAAAACQeUAUhv74/5d4QCfbFAoAuHdA5w1e///nckAOd3cKAGB3QFwzWP7/53JAc7BaCgBg
      d0CobVb9/+dyQMdiJAoAYHdAP3Q1/f/nckDG+RkKAGB3QAAAAAAAQHJAAAAAAADAeUA=
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAAFAAAAAAAAAAAWIBAAAAAAABQe0AAAAAAAKB+QAAAAAAAoHJAAAAAAADAe0AAAAAA
      AKBvQAAAAAAA4HZAAAAAAABQcEAAAAAAAJBzQAAAAAAAAHVAi+DaAgDockDB66r1/193QBnyoQAA
      mHhA8oiI9f+3d0CkzKcBAJh4QI1PpfX/t3dAWJKpAgCYeEA5ndv1/7d3QK/HpAMAmHhAE+wq9v+3
      d0BUAZcEAJh4QJR4kvb/t3dAGOp9BQCYeEByQxH3/7d3QGkJ+gUAmHhAYj1m9/+3d0AAAAAAAOB5
      QAAAAAAA4HVAAAAAAABge0AAAAAAAFB4QCa/Yv3/b3xA77jZ9f9vfEDrxEf+/298QHn9p/X/b3xA
      fHBN//9vfEBDl4n1/298QNdOffT/Q4FAQJQG9/8HfEAAAAAAAFiAQAAAAAAAUHtA
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAAHgAAAAAAAAAAEIRAAAAAAABgeEAAAAAAADCCQAAAAAAAwHxAyQThBABEgUCqz80D
      AAh8QNAoxwQARIFA7x1RBAAIfEABHIsEAESBQKGTOwUACHxAo9tDBABEgUC0IhkGAAh8QGIX8gMA
      RIFA7KjnBgAIfEDVmJYDAESBQB4ppQcACHxAjUEyAwBEgUAX0E8IAAh8QO0IxgIARIFAHPnlCAAI
      fEDE+VICAESBQPgxZgkACHxAvi/aAQBEgUCMPs8JAAh8QKbUXAEARIFA2xsgCgAIfECLHdwAAESB
      QIcCWAoACHxAwkdZAABEgUC9aHYKAAh8QNNCqQIAcHxAUeVUCgBwfEAAAAAAAIB9QAAAAAAASIBA
      AAAAAABogEAAAAAAAPCAQAAAAAAAGIRAAAAAAADAgEAGs8D8/xeFQNk6OAgA+H5AgyCk/P8XhUDM
      Hw0IAPh+QDlBQ/z/F4VAfqJaBwD4fkC2mOv7/xeFQLQDlgYA+H5AGP+d+/8XhUAvKMEFAPh+QK8z
      W/v/F4VAthzeBAD4fkAq2yP7/xeFQA0R7wMA+H5A+334+v8XhUCMUvYCAPh+QAuH2fr/F4VAdUb2
      AQD4fkAKHUf8/1eEQHvt9BAAGHdAAAAAAAAQhEAAAAAAAGB4QA==
  - !!python/object/apply:shapely.io.from_wkb
    - !!binary |
      AQMAAAABAAAAIQAAAAAAAAAAgIRAAAAAAADAbUAAAAAAAKCEQAAAAAAA0HVA7T4bAgBYhECPb2f2
      /xd3QFBMggIAWIRAUvnK9v8Xd0BBuPICAFiEQG88VPf/F3dAft9bAwBYhEAz4PL3/xd3QMi+vAMA
      WIRAgV2l+P8Xd0BLZxQEAFiEQEv8afn/F3dA6QBiBABYhEDQ1z76/xd3QFLMpAQAWIRASeMh+/8X
      d0DXJNwEAFiEQPLuEPz/F3dABoIHBQBYhEBzrQn9/xd3QPZ4JgUAWIRAirkJ/v8Xd0AG6UwEABiF
      QChSHfX/935AAAAAAAAYhkAAAAAAAHB8QAAAAAAAiIZAAAAAAAAQeUAAAAAAAIiGQAAAAAAAQGxA
      AAAAAAC4hUAAAAAAAMBXQK/awQQA6IRAO62dGQBgU0DAmCkFADSEQIiQqAMAkGlAckgMBQA0hEAW
      NqoFAJBpQB6G4gQANIRAQuSdBwCQaUC6uKwEADSEQCHLfgkAkGlA6WRrBAA0hEATSUgLAJBpQLwr
      HwQANIRAL/b1DACQaUAfycgDADSEQCCvgw4AkGlACxJpAwA0hEBYn+0PAJBpQHvyAAMANIRAgkow
      EQCQaUAja5ECADSEQByVSBIAkGlA/I4bAgA0hEAczDMTAJBpQJeAoAEANIRAm6vvEwCQaUBPwW0B
      ADSEQHASJxQAkGlAAAAAAACAhEAAAAAAAMBtQA==
  show_game: false
  state_size: 12
  track: !!python/object/apply:shapely.io.from_wkb
  - !!binary |
    AQMAAAACAAAAFQAAAAAAAAAAGIRAAAAAAAAATkAAAAAAAIiBQAAAAAAAAEZAAAAAAACQekAAAAAA
    AABHQAAAAAAAAGdAAAAAAABAVUAAAAAAACBkQAAAAAAAAFtAAAAAAAAAW0AAAAAAAJBwQAAAAAAA
    gFlAAAAAAACwfEAAAAAAAMBeQAAAAAAAMH5AAAAAAABAaEAAAAAAANB/QAAAAAAA0HRAAAAAAACw
    f0AAAAAAAFB3QAAAAAAAkHlAAAAAAADgeUAAAAAAAOB1QAAAAAAAYHtAAAAAAABQeEAAAAAAAIB9
    QAAAAAAASIBAAAAAAABogEAAAAAAAPCAQAAAAAAAGIRAAAAAAADAgEAAAAAAABiGQAAAAAAAcHxA
    AAAAAACIhkAAAAAAABB5QAAAAAAAiIZAAAAAAABAbEAAAAAAALiFQAAAAAAAwFdAAAAAAAAYhEAA
    AAAAAABOQBUAAAAAAAAAAICEQAAAAAAAwG1AAAAAAACghEAAAAAAANB1QAAAAAAAEIRAAAAAAABg
    eEAAAAAAADCCQAAAAAAAwHxAAAAAAABYgEAAAAAAAFB7QAAAAAAAoH5AAAAAAACgckAAAAAAAMB7
    QAAAAAAAoG9AAAAAAADgdkAAAAAAAFBwQAAAAAAAkHNAAAAAAAAAdUAAAAAAAEByQAAAAAAAwHlA
    AAAAAAAgcUAAAAAAAPB6QAAAAAAAAG5AAAAAAADgekAAAAAAAKBnQAAAAAAAoHlAAAAAAADgY0AA
    AAAAANB3QAAAAAAAoGVAAAAAAABQc0AAAAAAAEBrQAAAAAAAQGdAAAAAAADAbkAAAAAAAABkQAAA
    AAAAoHFAAAAAAAAAZEAAAAAAAJBzQAAAAAAA4GFAAAAAAADog0AAAAAAAGBlQAAAAAAAgIRAAAAA
    AADAbUA=
  walls:
  - - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAC4hUAAAAAAAMBXQAAAAAAAGIRAAAAAAAAATkA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAYhEAAAAAAAABOQAAAAAAAiIFAAAAAAAAARkA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACIgUAAAAAAAABGQAAAAAAAkHpAAAAAAAAAR0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACQekAAAAAAAABHQAAAAAAAAGdAAAAAAABAVUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAAZ0AAAAAAAEBVQAAAAAAAIGRAAAAAAAAAW0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAgZEAAAAAAAABbQAAAAAAAAFtAAAAAAACQcEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAAW0AAAAAAAJBwQAAAAAAAgFlAAAAAAACwfEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACAWUAAAAAAALB8QAAAAAAAwF5AAAAAAAAwfkA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADAXkAAAAAAADB+QAAAAAAAQGhAAAAAAADQf0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABAaEAAAAAAANB/QAAAAAAA0HRAAAAAAACwf0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADQdEAAAAAAALB/QAAAAAAAUHdAAAAAAACQeUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABQd0AAAAAAAJB5QAAAAAAA4HlAAAAAAADgdUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADgeUAAAAAAAOB1QAAAAAAAYHtAAAAAAABQeEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABge0AAAAAAAFB4QAAAAAAAgH1AAAAAAABIgEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACAfUAAAAAAAEiAQAAAAAAAaIBAAAAAAADwgEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABogEAAAAAAAPCAQAAAAAAAGIRAAAAAAADAgEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAYhEAAAAAAAMCAQAAAAAAAGIZAAAAAAABwfEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAYhkAAAAAAAHB8QAAAAAAAiIZAAAAAAAAQeUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACIhkAAAAAAABB5QAAAAAAAiIZAAAAAAABAbEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACIhkAAAAAAAEBsQAAAAAAAuIVAAAAAAADAV0A=
  - - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADog0AAAAAAAGBlQAAAAAAAgIRAAAAAAADAbUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACAhEAAAAAAAMBtQAAAAAAAoIRAAAAAAADQdUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACghEAAAAAAANB1QAAAAAAAEIRAAAAAAABgeEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAQhEAAAAAAAGB4QAAAAAAAMIJAAAAAAADAfEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAwgkAAAAAAAMB8QAAAAAAAWIBAAAAAAABQe0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABYgEAAAAAAAFB7QAAAAAAAoH5AAAAAAACgckA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACgfkAAAAAAAKByQAAAAAAAwHtAAAAAAACgb0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADAe0AAAAAAAKBvQAAAAAAA4HZAAAAAAABQcEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADgdkAAAAAAAFBwQAAAAAAAkHNAAAAAAAAAdUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACQc0AAAAAAAAB1QAAAAAAAQHJAAAAAAADAeUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABAckAAAAAAAMB5QAAAAAAAIHFAAAAAAADwekA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAgcUAAAAAAAPB6QAAAAAAAAG5AAAAAAADgekA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAAAAbkAAAAAAAOB6QAAAAAAAoGdAAAAAAACgeUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACgZ0AAAAAAAKB5QAAAAAAA4GNAAAAAAADQd0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADgY0AAAAAAANB3QAAAAAAAoGVAAAAAAABQc0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACgZUAAAAAAAFBzQAAAAAAAQGtAAAAAAABAZ0A=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAABAa0AAAAAAAEBnQAAAAAAAwG5AAAAAAAAAZEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAADAbkAAAAAAAABkQAAAAAAAoHFAAAAAAAAAZEA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACgcUAAAAAAAABkQAAAAAAAkHNAAAAAAADgYUA=
    - !!python/object/apply:shapely.io.from_wkb
      - !!binary |
        AQIAAAACAAAAAAAAAACQc0AAAAAAAOBhQAAAAAAA6INAAAAAAABgZUA=
  width: 800
eps_end: 0.1
eps_last_episode: 150
eps_start: 1.0
gamma: 0.99
hidden_sizes:
- 128
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
lr: 0.001
optimizer: !!python/name:torch.optim.adamw.AdamW ''
samples_per_epoch: 5000
sync_rate: 10
